telegram:
  api_id: 15882573
  api_hash: "dddd64edfc5326e4a35e448347b83e2d"
  token: "5841090279:AAEFdBGF5F7ELH9-vW5LbZ5x4h_MvUXzlCo"
  lang_code: !!str "en"
  max_upload_tasks: 5
  allowed_users:
    - id: 2094128105
      send_startup_message: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -00000000000
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
  api:
    upload_video_file: !!bool False
    upload_video_max_file_size: 2147483648
    upload_to_chat_ids:
      - 00000000000
      - -00000000000
    silent: !!bool False
    video_caption:
      include_title: !!bool True
      include_filename: !!bool False
      include_link: !!bool True
ytdlp:
  version_check_enabled: !!bool True
  version_check_interval: 86400
  notify_users_on_new_version: !!bool True
